/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  $(document).ready(function() {
    $('.news-slider-wrapper').append('<div class="next-prev-wrap"><span><a href="#" class="custom-prev">Previous</a></span><span><a href="#" class="custom-next">Next</a></span></div>');

    $('.news-slider').cycle({
        // fx:    'scrollLeft',
        // delay: -1000
    });

    $('.custom-prev').click(function(event) {
        event.preventDefault();
        $(this).parents('.news-slider-wrapper').find('.news-slider').cycle('prev');
        // $('.news-slider').cycle('prev');
    });

    $('.custom-next').click(function(event) {
        event.preventDefault();
        // $('.news-slider').cycle('next');
        $(this).parents('.news-slider-wrapper').find('.news-slider').cycle('next');
    });

});
})(jQuery, Drupal);
